---
title: "Analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages, message=FALSE}
library("edgeR")
```

Import

```{r import}
counts <- readDGE(files = Sys.glob("data/counts/*"))
```

Inspect

```{r inspect}
class(counts)
dim(counts)
head(colnames(counts))
str(counts)
```

Clean up

```{r clean-up}
samples <- basename(colnames(counts))
colnames(counts) <- samples
counts$samples$group <- samples
counts$samples
```

Standardize

```{r standardize}
counts$samples$lib.size
counts_cpm <- cpm(counts, log = TRUE)
```

Filter genes

```{r filter-genes}
plotDensities(counts_cpm, legend = FALSE)
counts_filtered <- counts[rowMeans(counts_cpm) > 0, , keep.lib.sizes = FALSE]
counts_filtered_cpm <- cpm(counts_filtered, log = TRUE)
plotDensities(counts_filtered_cpm, legend = FALSE)
```

Dimension reduction

```{r dimension-reduction}
plotMDS(counts_filtered_cpm)
plotMDS(counts_filtered_cpm, gene.selection = "common")
plotMDS(counts_filtered_cpm, dim.plot = c(3, 4))
```

limma+voom pipeline

```{r limma}
library("stringr")
y <- DGEList(counts = counts_filtered)
y <- calcNormFactors(y)
condition <- str_extract(samples, "[a-z]+")
design <- model.matrix(~0 + condition)
colnames(design) <- str_replace(colnames(design), "condition", "")
v <- voom(y, design)
fit <- lmFit(v, design)
cont_mat <- makeContrasts(gf.con = gf - con,
                          exgf.con = exgf - con,
                          exgf.gf = exgf - gf,
                          levels = design)
fit2 <- contrasts.fit(fit, contrasts = cont_mat)
fit2 <- eBayes(fit2)
results <- decideTests(fit2)
```

Venn Diagram using `limma::vennDiagram`

```{r vennDiagram}
vennDiagram(results)
```

Venn Diagram using UpSetR

```{r upset}
library("UpSetR")
upset(as.data.frame(abs(results)))
```
